In [1]:
import pandas as pd

# load data

In [2]:
df_trade = pd.read_csv('D:\\JupyterDir\\201502_202105\\201502_202105_trade.csv')

df_2mentions = pd.read_csv('D:\\JupyterDir\\201502_202105\\201502_202105_2mentions.csv')

df_mention = pd.read_csv('D:\\JupyterDir\\201502_202105\\201502_202105_mention.csv')

In [3]:
print(df_trade.shape)
df_trade.head()

(1520, 22)


time    country  Australia    Brunei     Canada      Chile       China  \
0  201502  Australia          0  39502042  127538913   91072981  4079619361   
1  201502     Brunei      31538         0     418484        428      283185   
2  201502     Canada   77357598    618272          0  103427697  3853895744   
3  201502      Chile   16410628        -1   47081781          0  1198198702   
4  201502      China         -1        -1         -1         -1           0   

   Hong Kong  India      Japan  ...  New Zealand        Peru  Philippines  \
0   84426352     -1  345053848  ...    566663030   129520038    449442858   
1     975641     -1    8088822  ...     52072991      346816       143387   
2   24059268     -1   83444263  ...    151640892  2022211448     31555316   
3   10218781     -1   12579002  ...     15407826   139001252      3875351   
4         -1     -1         -1  ...           -1          -1           -1   

      Russia  Singapore  South Korea     Taiwan   Thailand  United States  \
0   19122801   38762135      7494242  517852806  829241752     1601846133   
1      14744     550933           -1   35985255   12170098       12547977   
2  215220290   65129595     33216096   68881720  166774802    17493040494   
3   87440278    5109787      3169583    5087475   85783191      907448787   
4         -1         -1           -1         -1         -1             -1   

     Vietnam  
0  294873739  
1     797369  
2  189019323  
3   57367948  
4         -1  

[5 rows x 22 columns]

In [4]:
print(df_2mentions.shape)
df_2mentions.head()

(1520, 22)


time    country  Australia  Brunei  Canada  Chile   China  Hong Kong  \
0  201502  Australia     134507       0       0      0       0          0   
1  201502     Brunei          0     397       0      0       0          0   
2  201502     Canada          0       0   58231      0       0          0   
3  201502      Chile          0       0       0  10461       0          0   
4  201502      China          0       0       0      0  108444          0   

   India  Japan  ...  New Zealand  Peru  Philippines  Russia  Singapore  \
0      0      0  ...            0     0            0       0          0   
1      0      0  ...            0     0            0       0          0   
2      0      0  ...            0     0            0       0          0   
3      0      0  ...            0     0            0       0          0   
4      0      0  ...            0     0            0       0          0   

   South Korea  Taiwan  Thailand  United States  Vietnam  
0            0       0         0            120        0  
1            0       0         0              0        0  
2            0       0         0             94        0  
3            0       0         0              3        0  
4            0       0         0             24        0  

[5 rows x 22 columns]

In [5]:
print(df_mention.shape)
df_mention.head()

(1520, 22)


time    country  Australia  Brunei  Canada  Chile  China  Hong Kong  \
0  201502  Australia      89141       1    1166    313   1936         74   
1  201502     Brunei         12     101       3      2     33          3   
2  201502     Canada       1250       2   28194     45    553         61   
3  201502      Chile         62       0      50   1639     78          0   
4  201502      China       1350      30     504    141  28449       1302   

   India  Japan  ...  New Zealand  Peru  Philippines  Russia  Singapore  \
0   4784    896  ...         2493   173          174    1015        182   
1    406     16  ...            2     1            9      11          3   
2    191    307  ...           69    36          129     719         23   
3     46     72  ...            6   251           29     146          2   
4    448   1671  ...          191   101          274     811        284   

   South Korea  Taiwan  Thailand  United States  Vietnam  
0          222     152       510           8727      106  
1            4       1        11             56        3  
2          167      22        98          10021       55  
3           49       6        29            697       26  
4         1008    3543       327           4496      704  

[5 rows x 22 columns]

# Verify the same country name

In [6]:
col_trade = df_trade.columns
col_mention = df_mention.columns
col_2mentions = df_2mentions.columns

In [7]:
print(col_trade)
print(col_mention)
print(col_2mentions)
assert col_trade.all() == col_mention.all() == col_2mentions.all()

Index(['time', 'country', 'Australia', 'Brunei', 'Canada', 'Chile', 'China',
       'Hong Kong', 'India', 'Japan', 'Malaysia', 'Mexico', 'New Zealand',
       'Peru', 'Philippines', 'Russia', 'Singapore', 'South Korea', 'Taiwan',
       'Thailand', 'United States', 'Vietnam'],
      dtype='object')
Index(['time', 'country', 'Australia', 'Brunei', 'Canada', 'Chile', 'China',
       'Hong Kong', 'India', 'Japan', 'Malaysia', 'Mexico', 'New Zealand',
       'Peru', 'Philippines', 'Russia', 'Singapore', 'South Korea', 'Taiwan',
       'Thailand', 'United States', 'Vietnam'],
      dtype='object')
Index(['time', 'country', 'Australia', 'Brunei', 'Canada', 'Chile', 'China',
       'Hong Kong', 'India', 'Japan', 'Malaysia', 'Mexico', 'New Zealand',
       'Peru', 'Philippines', 'Russia', 'Singapore', 'South Korea', 'Taiwan',
       'Thailand', 'United States', 'Vietnam'],
      dtype='object')


In [8]:
column_list = df_trade.columns

# Concatenate each networks as features
A to B : <br>
X = [mention, 2mentions] <br>
&emsp; (e.g. <b>mention</b> means no. of news in country A mentions country B)<br>
Y = [trade] <br>
&emsp; (e.g. <b>trade</b> means country A for country B's <b>import trading among</b>)<br> 


## Full year

In [9]:
df_trade_fy = df_trade.iloc[:,2:]
df_mention_fy = df_mention.iloc[:,2:]
df_2mentions_fy = df_2mentions.iloc[:,2:]

print()

assert df_trade_fy.shape == df_mention_fy.shape == df_2mentions_fy.shape

Y = []
X = []

for i in range(df_trade_fy.shape[0]):
    for j in range(df_trade_fy.shape[1]):
        if df_trade_fy.iloc[i,j] > 0 and df_mention_fy.iloc[i,j] > 0 and df_2mentions_fy.iloc[i,j] > 0:
            X.append([df_mention_fy.iloc[i,j],df_2mentions_fy.iloc[i,j]])
            Y.append(df_trade_fy.iloc[i,j])

In [10]:
import numpy as np
X = np.array(X)
print(X.shape)
Y = np.array(Y)
print(Y.shape)

(20391, 2)
(20391,)


In [11]:
Y.reshape(-1,1).shape

(20391, 1)

In [12]:
print('mention vs trade:')
print(np.corrcoef(X[:,0],Y))
print('R square =', np.corrcoef(X[:,0],Y)[0,1]**2)

mention vs trade:
[[1.         0.39611456]
 [0.39611456 1.        ]]
R square = 0.15690674178663463


In [13]:
print('2mentions vs trade:')
print(np.corrcoef(X[:,1],Y))
print('R square =', np.corrcoef(X[:,1],Y)[0,1]**2)

2mentions vs trade:
[[1.        0.4391266]
 [0.4391266 1.       ]]
R square = 0.1928321690127169


## Drop some countries data

In [14]:
# new_country_list = \ # all countries
# ['Australia', 'Brunei', 'Canada', 
#  'Chile', 'China', 'Hong Kong', 
#  'India', 'Japan', 'Malaysia', 
#  'Mexico', 'New Zealand', 'Peru', 
#  'Philippines', 'Russia', 'Singapore', 
#  'South Korea', 'Taiwan', 'Thailand', 
#  'United States', 'Vietnam']


# 'Russia', drop the performance a lot. why???

new_country_list = \
['Australia', 'Brunei',
 'Canada', 'Chile', 
 'China', 'Hong Kong', 'India', 'Japan', 
 'Malaysia', 'Mexico', 'New Zealand', 
 'Peru', 'Philippines', 'Singapore', 'South Korea', 'Taiwan',
 'Thailand', 'United States', 'Vietnam']

In [15]:
print(df_trade.shape)

(1520, 22)


Collect rows by new_country_list // Drop 'Russia' by rows

In [16]:
df_trade_drop = df_trade.loc[df_trade['country'].isin(new_country_list)]
print(df_trade_drop.shape)
df_trade_drop.head()

(1444, 22)


time    country  Australia    Brunei     Canada      Chile       China  \
0  201502  Australia          0  39502042  127538913   91072981  4079619361   
1  201502     Brunei      31538         0     418484        428      283185   
2  201502     Canada   77357598    618272          0  103427697  3853895744   
3  201502      Chile   16410628        -1   47081781          0  1198198702   
4  201502      China         -1        -1         -1         -1           0   

   Hong Kong  India      Japan  ...  New Zealand        Peru  Philippines  \
0   84426352     -1  345053848  ...    566663030   129520038    449442858   
1     975641     -1    8088822  ...     52072991      346816       143387   
2   24059268     -1   83444263  ...    151640892  2022211448     31555316   
3   10218781     -1   12579002  ...     15407826   139001252      3875351   
4         -1     -1         -1  ...           -1          -1           -1   

      Russia  Singapore  South Korea     Taiwan   Thailand  United States  \
0   19122801   38762135      7494242  517852806  829241752     1601846133   
1      14744     550933           -1   35985255   12170098       12547977   
2  215220290   65129595     33216096   68881720  166774802    17493040494   
3   87440278    5109787      3169583    5087475   85783191      907448787   
4         -1         -1           -1         -1         -1             -1   

     Vietnam  
0  294873739  
1     797369  
2  189019323  
3   57367948  
4         -1  

[5 rows x 22 columns]

Collect columns by new_country_list // Drop 'Russia' by columns

In [17]:
df_trade_drop = df_trade_drop[['country','time']+new_country_list]
df_trade_drop = df_trade_drop.reset_index(drop=True)
print(df_trade_drop.shape)
df_trade_drop.head()

(1444, 21)


country    time  Australia    Brunei     Canada      Chile       China  \
0  Australia  201502          0  39502042  127538913   91072981  4079619361   
1     Brunei  201502      31538         0     418484        428      283185   
2     Canada  201502   77357598    618272          0  103427697  3853895744   
3      Chile  201502   16410628        -1   47081781          0  1198198702   
4      China  201502         -1        -1         -1         -1           0   

   Hong Kong  India      Japan  ...  Mexico  New Zealand        Peru  \
0   84426352     -1  345053848  ...      -1    566663030   129520038   
1     975641     -1    8088822  ...      -1     52072991      346816   
2   24059268     -1   83444263  ...      -1    151640892  2022211448   
3   10218781     -1   12579002  ...      -1     15407826   139001252   
4         -1     -1         -1  ...      -1           -1          -1   

   Philippines  Singapore  South Korea     Taiwan   Thailand  United States  \
0    449442858   38762135      7494242  517852806  829241752     1601846133   
1       143387     550933           -1   35985255   12170098       12547977   
2     31555316   65129595     33216096   68881720  166774802    17493040494   
3      3875351    5109787      3169583    5087475   85783191      907448787   
4           -1         -1           -1         -1         -1             -1   

     Vietnam  
0  294873739  
1     797369  
2  189019323  
3   57367948  
4         -1  

[5 rows x 21 columns]

In [18]:
df_mention_drop = df_mention.loc[df_mention['country'].isin(new_country_list)]
df_mention_drop = df_mention_drop[['country','time']+new_country_list]
df_mention_drop = df_mention_drop.reset_index(drop=True)

df_2mentions_drop = df_2mentions.loc[df_2mentions['country'].isin(new_country_list)]
df_2mentions_drop = df_2mentions_drop[['country','time']+new_country_list]
df_2mentions_drop = df_2mentions_drop.reset_index(drop=True)

Drop out columns named 'country' and 'time' 

In [19]:
df_trade_drop_clear = df_trade_drop.iloc[:,2:]
print(df_trade_drop_clear.shape)

df_mention_drop_clear = df_mention_drop.iloc[:,2:]
print(df_mention_drop_clear.shape)

df_2mentions_drop_clear = df_2mentions_drop.iloc[:,2:]
print(df_2mentions_drop_clear.shape)

df_trade_drop_clear.head()

(1444, 19)
(1444, 19)
(1444, 19)


Australia    Brunei     Canada      Chile       China  Hong Kong  India  \
0          0  39502042  127538913   91072981  4079619361   84426352     -1   
1      31538         0     418484        428      283185     975641     -1   
2   77357598    618272          0  103427697  3853895744   24059268     -1   
3   16410628        -1   47081781          0  1198198702   10218781     -1   
4         -1        -1         -1         -1           0         -1     -1   

       Japan    Malaysia  Mexico  New Zealand        Peru  Philippines  \
0  345053848  1241263608      -1    566663030   129520038    449442858   
1    8088822    11230239      -1     52072991      346816       143387   
2   83444263   913874176      -1    151640892  2022211448     31555316   
3   12579002   127518637      -1     15407826   139001252      3875351   
4         -1          -1      -1           -1          -1           -1   

   Singapore  South Korea     Taiwan   Thailand  United States    Vietnam  
0   38762135      7494242  517852806  829241752     1601846133  294873739  
1     550933           -1   35985255   12170098       12547977     797369  
2   65129595     33216096   68881720  166774802    17493040494  189019323  
3    5109787      3169583    5087475   85783191      907448787   57367948  
4         -1           -1         -1         -1             -1         -1

In [20]:
assert df_trade_drop_clear.shape == df_mention_drop_clear.shape == df_2mentions_drop_clear.shape

y = []
X = []

for i in range(df_trade_drop_clear.shape[0]):
    for j in range(df_trade_drop_clear.shape[1]):
        if df_trade_drop_clear.iloc[i,j] > 0 and df_mention_drop_clear.iloc[i,j] > 0 and df_2mentions_drop_clear.iloc[i,j] > 0:
            X.append([df_mention_drop_clear.iloc[i,j],df_2mentions_drop_clear.iloc[i,j]])
            y.append(df_trade_drop_clear.iloc[i,j])

In [21]:
X = np.array(X)
print(X.shape)
y = np.array(y)
print(Y.shape)
print()
print('mention vs trade:')
print(np.corrcoef(X[:,0],y))
print('R square =', np.corrcoef(X[:,0],y)[0,1]**2)
print()
print('2mentions vs trade:')
print(np.corrcoef(X[:,1],y))
print('R square =', np.corrcoef(X[:,1],y)[0,1]**2)

(18251, 2)
(20391,)

mention vs trade:
[[1.        0.5703996]
 [0.5703996 1.       ]]
R square = 0.3253557051202594

2mentions vs trade:
[[1.         0.55987555]
 [0.55987555 1.        ]]
R square = 0.3134606302117496


# Prediction